service: dataframe-storage-system

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  
  environment:
    METADATA_TABLE: ${self:service}-${self:provider.stage}
    CHUNK_SIZE: 100000
    AWS_REGION: ${self:provider.region}  # Added for bucket creation
    POWERTOOLS_SERVICE_NAME: ${self:service}  # For Lambda Powertools
    LOG_LEVEL: INFO
  
  httpApi:
    cors: true  # Enable CORS for all endpoints
    
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.METADATA_TABLE}"
        - Effect: Allow
          Action:
            - s3:CreateBucket
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucket
            - s3:DeleteObject
            - s3:ListObjects
            - s3:ListObjectsV2
            - s3:HeadBucket
          Resource:
            - "arn:aws:s3:::df-*"
            - "arn:aws:s3:::df-*/*"
        - Effect: Allow
          Action:
            - cognito-idp:AdminInitiateAuth
            - cognito-idp:AdminCreateUser
          Resource: "arn:aws:cognito-idp:${self:provider.region}:*:userpool/*"

layers:
  dependencies:
    path: layer
    description: Required dependencies for data frame processing
    compatibleRuntimes:
      - python3.9

package:
  patterns:
    - '!node_modules/**'
    - '!package*.json'
    - '!requirements.txt'
    - '!layer/**'
    - 'handlers/**/*.py'
    - '!.serverless/**'
    - '!.git/**'

functions:
  uploadDataFrame:
    handler: handlers/dataframes.upload
    timeout: 900
    memorySize: 3008
    layers:
      - {Ref: DependenciesLambdaLayer}
    events:
      - http:
          path: dataframes/upload
          method: post
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref ApiGatewayAuthorizer
          cors: true
    environment:
      POWERTOOLS_METRICS_NAMESPACE: ${self:service}-upload

  getDataFrame:
    handler: handlers/dataframes.get
    timeout: 900
    memorySize: 3008
    layers:
      - {Ref: DependenciesLambdaLayer}
    events:
      - http:
          path: dataframes/{name}
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: !Ref ApiGatewayAuthorizer
          cors: true
          request:
            parameters:
              paths:
                name: true
              querystrings:
                external_key: false
                use_last: false
    environment:
      POWERTOOLS_METRICS_NAMESPACE: ${self:service}-get

resources:
  Resources:
    MetadataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.METADATA_TABLE}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: df_path
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: df_path
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-user-pool-${self:provider.stage}
        
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref CognitoUserPool
        ClientName: ${self:service}-client-${self:provider.stage}
        GenerateSecret: false
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
          
    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: cognito-authorizer
        Type: COGNITO_USER_POOLS
        IdentitySource: method.request.header.Authorization
        RestApiId: !Ref ApiGatewayRestApi
        ProviderARNs:
          - !GetAtt CognitoUserPool.Arn

    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId: !Ref ApiGatewayRestApi
        
    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId: !Ref ApiGatewayRestApi

  Outputs:
    UserPoolId:
      Value: !Ref CognitoUserPool
    UserPoolClientId:
      Value: !Ref CognitoUserPoolClient
    ApiUrl:
      Value: !Sub https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${self:provider.stage}
